- name: create a info webpage
  hosts: all
  become: True
  become_user: root
  tasks:

    - name: install httpd package
      yum:
        name: httpd
        state: present

    - name: start httpd service
      systemd:
        name: httpd.service
        state: started
        enabled: True

    - name: write various information to webpage
      template:
        dest: /var/www/html/index.html
        src: index.html.j2

    - name: add header to httpd responses
      lineinfile:
        dest: /etc/httpd/conf.d/headers.conf
        line: "Header set X-Foo: foobar"
        regex: "Header set X-Foo:"
        create: True
      register: headers_conf

    - name: reload httpd service if needed
      systemd:
        service: httpd.service
        state: reloaded
      when: headers_conf is changed
