- name: create a info webpage
  hosts: all
  become: True
  become_user: root
  tasks:

    - name: install httpd package
      yum:
        name: httpd
        state: present

    - name: start httpd service
      systemd:
        name: httpd.service
        state: started
        enabled: True

    - name: write MAC address to webpage
      template:
        dest: /var/www/html/index.html
        src: index.html.j2
